apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
metadata:
  name: db-env

apiVersion: v1
kind: ConfigMap
data:
  KAFKA_SERVER: "192.168.236.194:9092"
metadata:
  name: kakfa-env